### ISSUE TITLE
Set a default colormap

### ISSUE THREAD

**Issue by Ceyron** [KeKsBoTer/vape4d#2]
Both the `vape4d.viewer` and the `vape4d.render` require setting a colormap. How about giving a default of `plt.get_cmap("RdBu_r")`?

**Comment by KeKsBoTer** [comment]
We could just use the default one 
```python
from matplotlib import pyplot as plt
plt.get_cmap()
```

**Comment by Ceyron** [comment]
That sounds reasonable :+1:
